# Generated by Django 4.1.1 on 2022-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='product_name',
            field=models.CharField(max_length=30),
        ),
    ]
