# Generated by Django 4.1.1 on 2022-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
