# Generated by Django 4.1.1 on 2022-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_report_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
