# Generated by Django 4.1.1 on 2022-09-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0011_alter_report_options_spentonshoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spentonshoes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
