# Generated by Django 4.1.1 on 2022-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_spentonshoes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
