# Generated by Django 4.1.1 on 2022-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_report_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spentonshoes',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
