# Generated by Django 4.1.1 on 2022-09-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyVendor',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('total_success', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['total_success'],
            },
        ),
        migrations.CreateModel(
            name='UserProxyExpenseByVendor',
            fields=[
                ('spent', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('proxy_vendor', models.ForeignKey(default='This vendor has stopped their operations!', on_delete=django.db.models.deletion.SET_DEFAULT, to='proxy.proxyvendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProxiesPerformance',
            fields=[
                ('total_success', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('proxy_vendor', models.ForeignKey(default='This vendor has stopped their operations!', on_delete=django.db.models.deletion.SET_DEFAULT, to='proxy.proxyvendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['total_success'],
            },
        ),
        migrations.CreateModel(
            name='ProxyExpenses',
            fields=[
                ('expense', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('proxy_vendor', models.OneToOneField(default='This vendor has stopped their operations!', on_delete=django.db.models.deletion.SET_DEFAULT, to='proxy.proxyvendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
