# Generated by Django 4.1.1 on 2022-09-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyvendor',
            options={'ordering': ['-total_success']},
        ),
        migrations.AlterModelOptions(
            name='userproxiesperformance',
            options={'ordering': ['-total_success']},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxy.proxyvendor'),
        ),
    ]
