# Generated by Django 4.1.1 on 2022-09-26 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxy', '0002_alter_proxyvendor_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProxyExpenses',
            new_name='ProxyExpense',
        ),
    ]
