# Generated by Django 4.1.1 on 2022-09-26 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxy', '0003_rename_proxyexpenses_proxyexpense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProxyExpense',
            new_name='ProxiesExpense',
        ),
    ]
