# Generated by Django 4.1.1 on 2022-09-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_rename_proxyexpense_proxiesexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
