# Generated by Django 4.1.1 on 2022-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_alter_proxy_options_alter_proxy_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
