# Generated by Django 4.1.1 on 2022-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_alter_proxy_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyvendor',
            name='number_of_decline',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxyvendor',
            name='number_of_time_bot_ran',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
