# Generated by Django 4.1.1 on 2022-09-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0007_proxyvendor_number_of_decline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxy.proxyvendor'),
        ),
        migrations.AlterField(
            model_name='userproxyexpensebyvendor',
            name='proxy_vendor',
            field=models.OneToOneField(default='This vendor has stopped their operations!', on_delete=django.db.models.deletion.SET_DEFAULT, to='proxy.proxyvendor'),
        ),
    ]
