# Generated by Django 4.1.1 on 2022-09-27 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxy', '0009_alter_userproxyexpensebyvendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproxyexpensebyvendor',
            name='proxy_vendor',
            field=models.OneToOneField(default='This vendor has stopped their operations!', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='proxy_expense_by_vendor', to='proxy.proxyvendor'),
        ),
        migrations.AlterField(
            model_name='userproxyexpensebyvendor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
