# Generated by Django 4.1.1 on 2022-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0013_alter_userproxyexpensebyvendor_proxy_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='created_at_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
