# Generated by Django 4.1.1 on 2022-09-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0014_proxy_created_at_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['-created_at_time']},
        ),
        migrations.RenameField(
            model_name='proxyvendor',
            old_name='number_of_time_bot_ran',
            new_name='number_of_time_proxy_used',
        ),
        migrations.AddField(
            model_name='userproxiesperformance',
            name='number_of_decline',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproxiesperformance',
            name='number_of_time_proxy_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxiesexpense',
            name='expense',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
