# Generated by Django 4.1.1 on 2022-09-28 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0016_proxytype_proxy_proxy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxytype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
