# Generated by Django 4.1.1 on 2022-09-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0018_alter_proxytype_proxy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproxiesperformance',
            name='proxy_type',
        ),
    ]
