# Generated by Django 4.1.1 on 2022-09-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0020_rename_number_of_time_proxy_used_userproxiesperformance_number_of_time_vendor_get_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxiesexpense',
            name='expense',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
