# Generated by Django 4.1.1 on 2022-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='selling_rate',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
