# Generated by Django 4.1.1 on 2022-09-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_id_alter_sellingmedium_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='selling_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sellingmedium'),
        ),
    ]
