# Generated by Django 4.1.1 on 2022-09-28 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotVendor',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('number_of_time_bot_ran', models.PositiveIntegerField(blank=True, null=True)),
                ('total_success', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_decline', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-total_success'],
            },
        ),
        migrations.CreateModel(
            name='UserBotPerformance',
            fields=[
                ('number_of_time_bot_ran', models.PositiveIntegerField(blank=True, null=True)),
                ('total_success', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_decline', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bot_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botvendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_success'],
            },
        ),
        migrations.CreateModel(
            name='SpentOnBot',
            fields=[
                ('expense', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotSubscription',
            fields=[
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bot_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.botvendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
