# Generated by Django 4.1.1 on 2022-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscription',
            name='one_time_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
