# Generated by Django 4.1.1 on 2022-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botsubscription_one_time_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscription',
            name='still_subscribed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
