# Generated by Django 4.1.1 on 2022-09-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botsubscription_still_subscribed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpentOnBot',
        ),
    ]
