# Generated by Django 4.1.1 on 2022-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_profile', '0004_alter_botprofile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botprofile',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='botprofile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
